### ISSUE TITLE
Jump to Connections

### ISSUE THREAD

**Issue by chgad** [mimischi/takemehome#1]
When clicking the Button "Take.Me.Home" the app could directly jump to the first connection.
That's what i would expect the  site to do.

**Comment by mimischi** [comment]
Are you saying: it should scroll down to the list automatically? We could do that!

**Comment by chgad** [comment]
Yep, taht's what i meant.

**Comment by mimischi** [comment]
It's implemented in the `store` branch and deployed to production.
